<?//= $job[array_rand($job)] ?>
<?php
$phil = array(
   "A. J. Ayer",
   "Bertrand Russel",
   "Patricia Churchland",
   "W. V. O. Quine",
   "Hillary Putnam",
   "David Chalmers",
   "Noam Chomsky",
   "Daniel Dennet",
   "Alvin Plantinga",
   "Thomas Hobbes",
   "Jean-Paul Sartre",
   "Martin Hediegger",
   "John Searle",
   "Peter Singer",
   "Saul Kripke"
);
$phil_cont = array(
   "Fyodor Dostoyevsky",
   "Paul Tillich",
   "Soren Kierkegaard",
   "Friedrich Nietzsche",
   "Franz Kafka",
   "Hannah Arendt",
   "Karl Barth",
   "Simone de Beauvoir",
   "Edmund Husserl",
   "William James",
   "Albert Camus",
   "Maurice Merleau-Ponty",
   "Jose Ortega",
   "Susan Bordo",
   "Judith Butler",
   "Judith Jarvis Thomson",
   "Angela Davis",
   "Guilles Deleuze",
   "Jacques Derrida",
   "Paulo Freire",
   "Felix Guattari",
   "Jurgen Habermas"
);
$trees = array(
   "Ash",
   "Aspen",
   "Oak",
   "Maple",
   "Hickory",
   "Hemlock",
   "Fir",
   "Elm",
   "Cottonwood",
   "Chestnut",
   "Cherry",
   "Birch",
   "Beech",
   "Basswood",
   "Pine",
   "Spruce",
   "Walnut"
);
$job = array(
   "HVAC",
   "Plumbing",
   "Electric",
   "Cleaning",
   "Painting"
);
$city = array(
   "Columbia",
   "Boston",
   "St. Louis",
   "Kansas City",
   "Palo Alto",
   "New York",
   "Chicago",
   "Providence",
   "Baltimore",
   "Los Angeles",
   "Houston",
   "Philadelphia",
   "Phoenix",
   "San Antonio",
   "San Diego",
   "Oakland",
   "Portland"
);
$state = array(
   "Alabama",
   "Alaska",
   "Arizona",
   "Arkansas",
   "California",
   "Colorado",
   "Connecticut",
   "Delaware",
   //"District Of Columbia",
   "Florida",
   "Georgia",
   "Hawaii",
   "Idaho",
   "Illinois",
   "Indiana",
   "Iowa",
   "Kansas",
   "Kentucky",
   "Louisiana",
   "Maine",
   "Maryland",
   "Massachusetts",
   "Michigan",
   "Minnesota",
   "Mississippi",
   "Missouri",
   "Montana",
   "Nebraska",
   "Nevada",
   "New Hampshire",
   "New Jersey",
   "New Mexico",
   "New York",
   "North Carolina",
   "North Dakota",
   "Ohio",
   "Oklahoma",
   "Oregon",
   "Pennsylvania",
   "Rhode Island",
   "South Carolina",
   "South Dakota",
   "Tennessee",
   "Texas",
   "Utah",
   "Vermont",
   "Virginia",
   "Washington",
   "West Virginia",
   "Wisconsin",
   "Wyoming"
);
$units = array(
   "Joules",
   "Pounds",
   "Boxes",
   "Units",
   "Watts",
   "Newtons",
   "Crates"
);
$project = array(
   "Solar Ice Melt Strip for Roof",
   "Banana Saver",
   "Foam Forts",
   "Air Conditioning Mattress",
   "Power2go",
   "Icebreaker Snow Shovel",
   "Space-War Drone",
   "Pillow Clip",
   "Water Bottle Storage",
   "Modular Growing Wall",
   "Stirring Gloves",
   "Push Hooks",
   "ECO Bin",
   "Beam",
   "Sidwalk Chalk Printer",
);
$imgProfile = array(
   "adellecharles-73.jpg",
   "alagoon-73.jpg",
   "brenton_clarke-73.jpg",
   "chexee-73.jpg",
   "commadelimited-73.jpg",
   "dancounsell-73.jpg"
);
$company = array(
   "SE",
   "Wood Solutions",
   "Pear Crafts",
   "Orange Works",
   "Kale Associates"
);
?>